### PR TITLE
enhancing the creation of remote conf

### PR DESCRIPTION
**Pull request by PeninaSchuss**

### CODE REVIEW

**Review by pepgid — CHANGES_REQUESTED** [review]
Why are these changes submitted? It is s very unclear.
Some of the changes are in a later pull request

**Comment by PeninaSchuss** [comment]
I added prev changes later pull request because once you told me that when doing a pull request, and then creating a new branch, it should branch from the branch of that pull request, so after merging the new branch should be clode to int. so maybe i did not understand correctly...

**Comment by pepgid** [comment]
At t1 a branch with changes might be separate. At T2 if a developer builds
up n the changes they have a dependency and if the initial pull request is
pending it becomes obsolete.

**Comment by PeninaSchuss** [comment]
I understand.
When I can, is it necessary for me to create new pull requests, or should we leave it like that?

**Pull request closed without merging**
